import { X } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import type { AttendanceDisplayRecord } from "../types/staffOperations";
import { formatMinutes } from "../utils/staffOperations";
import { AttendanceStatusBadge } from "./AttendanceStatusBadge";

export function AttendanceDetailSheet({ record, open, locale, onOpenChange }: { record: AttendanceDisplayRecord | null; open: boolean; locale: string; onOpenChange: (open: boolean) => void }) {
  const { t } = useTranslation("staffDetail"); if (!record) return null;
  const time = (value?: string | null) => value ? new Date(value).toLocaleTimeString(locale, { hour: "2-digit", minute: "2-digit" }) : "—";
  const rows = [[t("attendance.columns.scheduled"), record.schedule && !record.schedule.isOff ? `${record.schedule.startTime} – ${record.schedule.endTime}` : t("schedule.off")], [t("attendance.columns.checkIn"), time(record.attendance?.checkIn)], [t("attendance.columns.checkOut"), time(record.attendance?.checkOut)], [t("attendance.columns.worked"), record.attendance ? formatMinutes(record.attendance.workMinutes) : "—"], [t("attendance.columns.late"), record.attendance?.lateMinutes ? formatMinutes(record.attendance.lateMinutes) : t("today.onTime")], [t("attendance.columns.overtime"), record.overtimeMinutes ? formatMinutes(record.overtimeMinutes) : "—"]];
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="w-full sm:max-w-md"><SheetHeader className="border-b px-6 py-5 pr-14"><SheetTitle>{t("attendance.detailTitle")}</SheetTitle><SheetDescription>{t("attendance.detailDescription")}</SheetDescription></SheetHeader><SheetClose asChild><Button variant="ghost" size="icon-sm" className="absolute right-3 top-3 size-11 rounded-full sm:right-4 sm:top-4 sm:size-8" aria-label={t("common:actions.close")}><X aria-hidden="true" /></Button></SheetClose><div className="space-y-5 px-6 py-5"><div><p className="text-lg font-semibold">{new Date(`${record.date}T00:00:00`).toLocaleDateString(locale, { weekday: "long", month: "long", day: "numeric", year: "numeric" })}</p><div className="mt-2"><AttendanceStatusBadge status={record.status} /></div></div><dl className="divide-y rounded-xl border">{rows.map(([label, value]) => <div key={label} className="flex items-center justify-between gap-4 px-4 py-3"><dt className="text-sm text-muted-foreground">{label}</dt><dd className="text-right text-sm font-semibold tabular-nums">{value}</dd></div>)}</dl>{record.timeOff && <div className="rounded-xl border bg-muted/30 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{t("attendance.timeOff")}</p><p className="mt-2 text-sm font-medium">{t("statuses.approved_leave")}</p><p className="mt-1 text-sm text-muted-foreground">{record.timeOff.reason || t("workforce:timeOff.noReason")}</p></div>}{record.attendance?.note && <p className="rounded-xl bg-muted/30 p-4 text-sm text-muted-foreground">{record.attendance.note}</p>}</div></SheetContent></Sheet>;
}
