import { useMemo, useState } from "react";
import { CalendarX2 } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import type { AttendanceRangePreset } from "../hooks/useStaffOperations";
import type { AttendanceDisplayRecord, AttendanceDisplayStatus } from "../types/staffOperations";
import { formatMinutes } from "../utils/staffOperations";
import { AttendanceDetailSheet } from "./AttendanceDetailSheet";
import { AttendanceStatusBadge } from "./AttendanceStatusBadge";

const exceptionStatuses: ("ALL" | AttendanceDisplayStatus)[] = ["ALL", "LATE", "ABSENT", "APPROVED_LEAVE", "SCHEDULED_OFF"];
export function StaffAttendanceTab({ records, loading, preset, setPreset, customFrom, setCustomFrom, customTo, setCustomTo, locale }: { records: AttendanceDisplayRecord[]; loading: boolean; preset: AttendanceRangePreset; setPreset: (value: AttendanceRangePreset) => void; customFrom: string; setCustomFrom: (value: string) => void; customTo: string; setCustomTo: (value: string) => void; locale: string }) {
  const { t } = useTranslation("staffDetail"); const [filter, setFilter] = useState<"ALL" | AttendanceDisplayStatus>("ALL"); const [selected, setSelected] = useState<AttendanceDisplayRecord | null>(null);
  const filtered = useMemo(() => filter === "ALL" ? records : records.filter((item) => item.status === filter), [filter, records]);
  const summary = useMemo(() => ({ scheduled: records.filter((item) => item.schedule && !item.schedule.isOff).length, worked: records.filter((item) => item.attendance?.checkIn).length, late: records.filter((item) => item.status === "LATE").length, absent: records.filter((item) => item.status === "ABSENT").length, leave: records.filter((item) => item.status === "APPROVED_LEAVE").length, off: records.filter((item) => item.status === "SCHEDULED_OFF").length, work: records.reduce((sum, item) => sum + (item.attendance?.workMinutes ?? 0), 0), overtime: records.reduce((sum, item) => sum + item.overtimeMinutes, 0) }), [records]);
  const time = (value?: string | null) => value ? new Date(value).toLocaleTimeString(locale, { hour: "2-digit", minute: "2-digit" }) : "—"; const scheduleLabel = (record: AttendanceDisplayRecord) => record.schedule && !record.schedule.isOff ? `${record.schedule.startTime} – ${record.schedule.endTime}` : t("schedule.off");
  return <div className="space-y-5"><header><h2 className="text-lg font-semibold">{t("attendance.title")}</h2><p className="mt-1 text-sm text-muted-foreground">{t("attendance.description")}</p></header><section className="grid gap-3 rounded-xl border bg-card p-3 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_1fr]" aria-label={t("attendance.title")}><div className="space-y-1.5"><Label>{t("attendance.range.month")}</Label><Select value={preset} onValueChange={(value) => setPreset(value as AttendanceRangePreset)}><SelectTrigger className="min-h-11"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="WEEK">{t("attendance.range.week")}</SelectItem><SelectItem value="MONTH">{t("attendance.range.month")}</SelectItem><SelectItem value="PREVIOUS_MONTH">{t("attendance.range.previousMonth")}</SelectItem><SelectItem value="CUSTOM">{t("attendance.range.custom")}</SelectItem></SelectContent></Select></div><div className="space-y-1.5"><Label>{t("attendance.filter")}</Label><Select value={filter} onValueChange={(value) => setFilter(value as typeof filter)}><SelectTrigger className="min-h-11"><SelectValue /></SelectTrigger><SelectContent>{exceptionStatuses.map((status) => <SelectItem key={status} value={status}>{status === "ALL" ? t("attendance.all") : t(`statuses.${status.toLowerCase()}`)}</SelectItem>)}</SelectContent></Select></div>{preset === "CUSTOM" && <div className="grid grid-cols-2 gap-2"><div className="space-y-1.5"><Label htmlFor="attendance-from">{t("attendance.from")}</Label><Input id="attendance-from" type="date" value={customFrom} onChange={(event) => setCustomFrom(event.target.value)} /></div><div className="space-y-1.5"><Label htmlFor="attendance-to">{t("attendance.to")}</Label><Input id="attendance-to" type="date" value={customTo} onChange={(event) => setCustomTo(event.target.value)} /></div></div>}</section>
    <section><h3 className="text-sm font-semibold">{t("attendance.summary")}</h3><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-8">{[["scheduledDays",summary.scheduled],["workedDays",summary.worked],["lateDays",summary.late],["absentDays",summary.absent],["leaveDays",summary.leave],["offDays",summary.off],["totalWork",formatMinutes(summary.work)],["overtime",formatMinutes(summary.overtime)]].map(([label, value]) => <Card key={label} className="gap-0 py-0 shadow-xs"><CardContent className="p-3"><p className="text-[11px] text-muted-foreground">{t(`attendance.${label}`)}</p><p className="mt-1 text-base font-bold tabular-nums">{value}</p></CardContent></Card>)}</div></section>
    {loading && <Card className="py-0"><CardContent className="space-y-1 p-1">{Array.from({ length: 7 }, (_, index) => <Skeleton key={index} className="h-16" />)}</CardContent></Card>}
    {!loading && filtered.length === 0 && <Card><CardContent className="flex min-h-56 flex-col items-center justify-center text-center"><CalendarX2 className="size-9 text-muted-foreground" aria-hidden="true" /><p className="mt-4 font-semibold">{filter === "ALL" ? t("attendance.empty") : t("attendance.emptyFiltered")}</p></CardContent></Card>}
    {!loading && filtered.length > 0 && <><div className="hidden overflow-hidden rounded-xl border bg-card shadow-xs lg:block"><table className="w-full text-left"><thead className="border-b bg-muted/35"><tr>{(["date","scheduled","checkIn","checkOut","worked","late","overtime","status"] as const).map((column) => <th key={column} className="px-4 py-3 text-xs font-semibold text-muted-foreground">{t(`attendance.columns.${column}`)}</th>)}</tr></thead><tbody className="divide-y">{filtered.map((record) => <tr key={record.key} className="cursor-pointer hover:bg-muted/25" tabIndex={0} onClick={() => setSelected(record)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setSelected(record); }}><td className="px-4 py-3 text-sm font-medium">{new Date(`${record.date}T00:00:00`).toLocaleDateString(locale, { month: "short", day: "numeric" })}</td><td className="px-4 py-3 font-mono text-xs tabular-nums">{scheduleLabel(record)}</td><td className="px-4 py-3 font-mono text-xs tabular-nums">{time(record.attendance?.checkIn)}</td><td className="px-4 py-3 font-mono text-xs tabular-nums">{time(record.attendance?.checkOut)}</td><td className="px-4 py-3 text-sm tabular-nums">{record.attendance ? formatMinutes(record.attendance.workMinutes) : "—"}</td><td className="px-4 py-3 text-sm tabular-nums">{record.attendance?.lateMinutes ? formatMinutes(record.attendance.lateMinutes) : t("today.onTime")}</td><td className="px-4 py-3 text-sm tabular-nums">{record.overtimeMinutes ? formatMinutes(record.overtimeMinutes) : "—"}</td><td className="px-4 py-3"><AttendanceStatusBadge status={record.status} /></td></tr>)}</tbody></table></div><div className="grid gap-3 sm:grid-cols-2 lg:hidden">{filtered.map((record) => <Card key={record.key} className="gap-0 py-0 shadow-xs"><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{new Date(`${record.date}T00:00:00`).toLocaleDateString(locale, { weekday: "short", month: "short", day: "numeric" })}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{scheduleLabel(record)}</p></div><AttendanceStatusBadge status={record.status} /></div><dl className="mt-4 grid grid-cols-3 gap-3 text-xs"><div><dt className="text-muted-foreground">{t("attendance.columns.checkIn")}</dt><dd className="mt-1 font-medium tabular-nums">{time(record.attendance?.checkIn)}</dd></div><div><dt className="text-muted-foreground">{t("attendance.columns.checkOut")}</dt><dd className="mt-1 font-medium tabular-nums">{time(record.attendance?.checkOut)}</dd></div><div><dt className="text-muted-foreground">{t("attendance.columns.worked")}</dt><dd className="mt-1 font-medium tabular-nums">{record.attendance ? formatMinutes(record.attendance.workMinutes) : "—"}</dd></div></dl><Button variant="outline" className="mt-4 min-h-11 w-full" onClick={() => setSelected(record)}>{t("attendance.detailTitle")}</Button></CardContent></Card>)}</div></>}
    <AttendanceDetailSheet record={selected} open={Boolean(selected)} locale={locale} onOpenChange={(open) => { if (!open) setSelected(null); }} />
  </div>;
}
