import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Pencil } from "lucide-react";
import { useTranslation } from "react-i18next";
import dayjs from "@/lib/dayjs";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import type { Staff, StaffScheduleDay, StaffScheduleOffDay } from "../types/staff";
import type { AttendanceDisplayRecord } from "../types/staffOperations";
import { AttendanceStatusBadge } from "./AttendanceStatusBadge";
import { EditScheduleSheet } from "../../workforce/components/EditScheduleSheet";

export function StaffScheduleTab({ staff, schedule, offDays, records, locale, saving, onSave }: { staff: Staff; schedule: StaffScheduleDay[]; offDays: StaffScheduleOffDay[]; records: AttendanceDisplayRecord[]; locale: string; saving: boolean; onSave: (staffId: string, schedule: StaffScheduleDay[]) => Promise<boolean> }) {
  const { t } = useTranslation("staffDetail"); const [anchor, setAnchor] = useState(dayjs()); const [editing, setEditing] = useState(false);
  const start = anchor.startOf("week"); const dates = Array.from({ length: 7 }, (_, index) => start.add(index, "day")); const scheduleByDay = useMemo(() => new Map(schedule.map((item) => [item.dayOfWeek, item])), [schedule]); const recordByDate = useMemo(() => new Map(records.map((item) => [item.date, item])), [records]);
  return <div className="space-y-5"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-lg font-semibold">{t("schedule.title")}</h2><p className="mt-1 text-sm text-muted-foreground">{t("schedule.description")}</p></div><Button className="min-h-11" onClick={() => setEditing(true)}><Pencil aria-hidden="true" />{t("editSchedule")}</Button></header><div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border bg-card p-3"><Button variant="outline" size="icon" className="size-11" aria-label={t("schedule.previous")} onClick={() => setAnchor((value) => value.subtract(7, "day"))}><ChevronLeft aria-hidden="true" /></Button><p className="text-sm font-semibold tabular-nums">{start.toDate().toLocaleDateString(locale, { month: "short", day: "numeric" })} – {start.add(6, "day").toDate().toLocaleDateString(locale, { month: "short", day: "numeric", year: "numeric" })}</p><div className="flex gap-2"><Button variant="ghost" className="min-h-11" onClick={() => setAnchor(dayjs())}>{t("schedule.today")}</Button><Button variant="outline" size="icon" className="size-11" aria-label={t("schedule.next")} onClick={() => setAnchor((value) => value.add(7, "day"))}><ChevronRight aria-hidden="true" /></Button></div></div><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-7">{dates.map((date) => { const item = scheduleByDay.get(date.day()); const record = recordByDate.get(date.format("YYYY-MM-DD")); const working = Boolean(item && !item.isOff); return <Card key={date.format("YYYY-MM-DD")} className="gap-0 py-0 shadow-xs"><CardContent className="p-4"><p className="text-xs font-medium capitalize text-muted-foreground">{date.toDate().toLocaleDateString(locale, { weekday: "long" })}</p><p className="mt-1 text-sm font-semibold tabular-nums">{working && item ? `${item.startTime} – ${item.endTime}` : t("schedule.off")}</p><div className="mt-3">{record ? <AttendanceStatusBadge status={record.status} /> : <span className="text-xs text-muted-foreground">{working ? t("schedule.workingDay") : t("schedule.off")}</span>}</div></CardContent></Card>; })}</section>{editing && <EditScheduleSheet open item={{ staff, schedule: { shopId: staff.shopId, staffId: staff.id, schedule, offDays } }} isSaving={saving} onOpenChange={setEditing} onSave={onSave} />}</div>;
}
