import { CalendarClock, Clock3, LogIn, TimerReset } from "lucide-react";
import { useTranslation } from "react-i18next";
import dayjs from "@/lib/dayjs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { AttendanceDisplayRecord } from "../types/staffOperations";
import { formatMinutes } from "../utils/staffOperations";
import { AttendanceStatusBadge } from "./AttendanceStatusBadge";

export function StaffOverviewTab({ records, pendingCount, locale }: { records: AttendanceDisplayRecord[]; pendingCount: number; locale: string }) {
  const { t } = useTranslation("staffDetail"); const todayKey = dayjs().format("YYYY-MM-DD"); const today = records.find((item) => item.date === todayKey); const weekMinutes = records.reduce((sum, item) => sum + (item.attendance?.workMinutes ?? 0), 0);
  const checkIn = today?.attendance?.checkIn ? new Date(today.attendance.checkIn).toLocaleTimeString(locale, { hour: "2-digit", minute: "2-digit" }) : t("today.noCheckIn");
  const summary = [{ label: t("today.schedule"), value: today?.schedule && !today.schedule.isOff ? `${today.schedule.startTime} – ${today.schedule.endTime}` : t("schedule.off"), icon: CalendarClock }, { label: t("today.attendance"), value: checkIn, icon: LogIn }, { label: t("today.late"), value: today?.attendance?.lateMinutes ? formatMinutes(today.attendance.lateMinutes) : t("today.onTime"), icon: TimerReset }, { label: t("today.week"), value: formatMinutes(weekMinutes), icon: Clock3 }];
  return <div className="space-y-5"><div><h2 className="text-lg font-semibold">{t("overview.title")}</h2><p className="mt-1 text-sm text-muted-foreground">{t("overview.description")}</p></div><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summary.map((item) => <Card key={item.label} className="gap-0 py-0 shadow-xs"><CardContent className="flex items-center gap-3 p-4"><span className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary"><item.icon className="size-4" aria-hidden="true" /></span><div className="min-w-0"><p className="text-xs text-muted-foreground">{item.label}</p><p className="mt-1 truncate text-sm font-semibold tabular-nums">{item.value}</p></div></CardContent></Card>)}</section><Card><CardHeader><CardTitle>{t("today.title")}</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[[t("today.schedule"), today?.schedule && !today.schedule.isOff ? `${today.schedule.startTime} – ${today.schedule.endTime}` : t("schedule.off")], [t("today.checkIn"), checkIn], [t("today.checkOut"), today?.attendance?.checkOut ? new Date(today.attendance.checkOut).toLocaleTimeString(locale, { hour: "2-digit", minute: "2-digit" }) : "—"], [t("today.worked"), today?.attendance ? formatMinutes(today.attendance.workMinutes) : "—"], [t("today.late"), today?.attendance?.lateMinutes ? formatMinutes(today.attendance.lateMinutes) : t("today.onTime")]].map(([label, value]) => <div key={label} className="rounded-lg border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold tabular-nums">{value}</p></div>)}<div className="rounded-lg border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">{t("today.status")}</p><div className="mt-1">{today ? <AttendanceStatusBadge status={today.status} /> : "—"}</div></div></CardContent></Card><Card className="gap-0 py-0"><CardContent className="flex items-center justify-between gap-4 p-4"><div><p className="text-sm font-semibold">{t("today.pending")}</p><p className="mt-1 text-xs text-muted-foreground">{pendingCount ? t("timeOff.pending") : t("today.noPending")}</p></div><span className="min-w-9 rounded-full bg-muted px-2 py-1 text-center text-sm font-semibold tabular-nums">{pendingCount}</span></CardContent></Card></div>;
}
