const service = {
  page: { eyebrow: "Service workspace", title: "Services", description: "Manage your salon services, pricing and availability." },
  actions: { add: "Add service", createCategory: "New category", changeStatus: "Change service status", edit: "Edit service", expand: "Show service options", collapse: "Hide service options", viewOptions: "View options", hideOptions: "Hide options" },
  overview: { label: "Service overview", all: "All services", active: "Active", hidden: "Hidden", categories: "Categories" },
  toolbar: { label: "Service filters" },
  search: { label: "Search services", placeholder: "Search services...", clear: "Clear search" },
  filters: { all: "All", active: "Active", inactive: "Hidden", clear: "Clear filters" },
  sort: { label: "Sort", name: "Name", price: "Price", duration: "Duration" },
  fields: { service: "Service", category: "Category", status: "Status", priceDuration: "Price · Duration" },
  status: { active: "Active", hidden: "Hidden" },
  service: { optionGroups: "option group", noOptions: "No options", uncategorized: "Uncategorized", required: "Required" },
  units: { minutes: "min", pricePrefix: "+" },
  empty: { title: "No services yet", description: "Create your first service to start accepting appointments.", filteredTitle: "No matching services", filteredDescription: "Try a different search or clear the current filters." },
  messages: { loadError: "Unable to load services", refreshHint: "Refresh the page and try again." },
  pagination: { showing: "Showing {{start}}–{{end}} of {{total}} services", previous: "Previous", next: "Next", page: "Page {{current}} of {{total}}" },
  category: { eyebrow: "Service catalog", viewTitle: "Service categories", viewDescription: "Keep treatments organised so your team and customers can find them faster.", total: "{{count}} categories", moreCount: "{{count}} more categories", viewAll: "View all categories", serviceCount: "{{count}} services", loading: "Loading categories", refreshHint: "Refresh the page and try again.", retry: "Try again", viewEmptyDescription: "Create a category to organise your service menu.", createTitle: "Create service category", createDescription: "Group services so customers can find the right treatment faster.", nameLabel: "Category name", namePlaceholder: "e.g. Manicure", nameHint: "Use a short, recognisable name (up to 100 characters).", nameRequired: "Category name is required.", nameTooLong: "Category name must be 100 characters or fewer.", existingTitle: "Existing categories", existingDescription: "These categories are already available for your shop.", empty: "No categories yet.", create: "Create category", creating: "Creating…", cancel: "Cancel", close: "Close category form", loadError: "Unable to load categories", createError: "Unable to create category" },
  editor: { createTitle: "Add service", createDescription: "Create a service and preview how it will appear to customers.", editTitle: "Edit service", editDescription: "Update service details and review the customer-facing preview.", basicInformation: "Basic information", image: "Service image", imageHint: "JPG, PNG or WebP up to 5 MB.", name: "Service name", namePlaceholder: "e.g. Gel manicure", category: "Category", newCategory: "New category", categoryPlaceholder: "Select a category", categoriesLoading: "Loading categories…", noCategory: "Uncategorised", price: "Price", duration: "Duration (minutes)", sortOrder: "Display order", description: "Description", descriptionPlaceholder: "A short description of this service…", active: "Available for booking", activeHint: "Customers can book this service when it is active.", options: "Options", optionsDescription: "Add choices such as shape, size or finish.", addOptionGroup: "Add option group", remove: "Remove", cancel: "Cancel", reset: "Reset", save: "Save service", saving: "Saving…", create: "Create service", creating: "Creating…", preview: "Customer preview", previewDescription: "This is how the service will appear in the booking flow.", loadError: "Unable to load this service", saveError: "Unable to save this service", categoriesError: "Unable to load categories", retry: "Try again", imagePreview: "Service image preview", option: "Service option", optionPlaceholder: "e.g. Shape, size", valuePlaceholder: "Option value", pricePlaceholder: "Price", minutesPlaceholder: "Min", required: "Required", addValue: "Add value", previewImage: "Service image", previewCategory: "Category", previewFrom: "From", previewTotal: "Total", previewBook: "Book now" },
};
export default service;
