const service = {
  page: { eyebrow: "Không gian dịch vụ", title: "Dịch vụ", description: "Quản lý dịch vụ, giá và trạng thái hoạt động của salon." },
  actions: { add: "Thêm dịch vụ", createCategory: "Tạo danh mục", changeStatus: "Đổi trạng thái dịch vụ", edit: "Chỉnh sửa dịch vụ", expand: "Xem tuỳ chọn dịch vụ", collapse: "Ẩn tuỳ chọn dịch vụ", viewOptions: "Xem tuỳ chọn", hideOptions: "Ẩn tuỳ chọn" },
  overview: { label: "Tổng quan dịch vụ", all: "Tất cả dịch vụ", active: "Đang hoạt động", hidden: "Đã ẩn", categories: "Danh mục" },
  toolbar: { label: "Bộ lọc dịch vụ" },
  search: { label: "Tìm kiếm dịch vụ", placeholder: "Tìm kiếm dịch vụ...", clear: "Xoá tìm kiếm" },
  filters: { all: "Tất cả", active: "Đang hoạt động", inactive: "Đã ẩn", clear: "Xoá bộ lọc" },
  sort: { label: "Sắp xếp", name: "Tên", price: "Giá", duration: "Thời lượng" },
  fields: { service: "Dịch vụ", category: "Danh mục", status: "Trạng thái", priceDuration: "Giá · Thời lượng" },
  status: { active: "Đang hoạt động", hidden: "Đã ẩn" },
  service: { optionGroups: "nhóm tuỳ chọn", noOptions: "Không có tuỳ chọn", uncategorized: "Chưa phân loại", required: "Bắt buộc" },
  units: { minutes: "phút", pricePrefix: "+" },
  empty: { title: "Chưa có dịch vụ", description: "Tạo dịch vụ đầu tiên để bắt đầu nhận lịch hẹn.", filteredTitle: "Không tìm thấy dịch vụ", filteredDescription: "Hãy thử từ khoá khác hoặc xoá bộ lọc hiện tại." },
  messages: { loadError: "Không thể tải danh sách dịch vụ", refreshHint: "Hãy tải lại trang và thử lại." },
  pagination: { showing: "Hiển thị {{start}}–{{end}} trong {{total}} dịch vụ", previous: "Trước", next: "Sau", page: "Trang {{current}}/{{total}}" },
  category: { eyebrow: "Danh mục dịch vụ", viewTitle: "Các danh mục dịch vụ", viewDescription: "Sắp xếp liệu trình rõ ràng để đội ngũ và khách hàng tìm nhanh hơn.", total: "{{count}} danh mục", moreCount: "{{count}} danh mục khác", viewAll: "Xem tất cả danh mục", serviceCount: "{{count}} dịch vụ", loading: "Đang tải danh mục", refreshHint: "Hãy tải lại trang và thử lại.", retry: "Thử lại", viewEmptyDescription: "Tạo danh mục để sắp xếp menu dịch vụ của shop.", createTitle: "Tạo danh mục dịch vụ", createDescription: "Nhóm các dịch vụ để khách hàng tìm được liệu trình phù hợp nhanh hơn.", nameLabel: "Tên danh mục", namePlaceholder: "Ví dụ: Chăm sóc móng", nameHint: "Đặt tên ngắn, dễ nhận biết (tối đa 100 ký tự).", nameRequired: "Vui lòng nhập tên danh mục.", nameTooLong: "Tên danh mục không được quá 100 ký tự.", existingTitle: "Danh mục hiện có", existingDescription: "Các danh mục này đang được dùng trong shop.", empty: "Chưa có danh mục.", create: "Tạo danh mục", creating: "Đang tạo…", cancel: "Huỷ", close: "Đóng form danh mục", loadError: "Không thể tải danh mục", createError: "Không thể tạo danh mục" },
  editor: { createTitle: "Thêm dịch vụ", createDescription: "Tạo dịch vụ và xem trước cách hiển thị với khách hàng.", editTitle: "Chỉnh sửa dịch vụ", editDescription: "Cập nhật thông tin và kiểm tra preview dành cho khách hàng.", basicInformation: "Thông tin cơ bản", image: "Ảnh dịch vụ", imageHint: "JPG, PNG hoặc WebP tối đa 5 MB.", name: "Tên dịch vụ", namePlaceholder: "Ví dụ: Gel manicure", category: "Danh mục", newCategory: "Tạo danh mục", categoryPlaceholder: "Chọn danh mục", categoriesLoading: "Đang tải danh mục…", noCategory: "Chưa phân loại", price: "Giá", duration: "Thời lượng (phút)", sortOrder: "Thứ tự hiển thị", description: "Mô tả", descriptionPlaceholder: "Mô tả ngắn về dịch vụ…", active: "Cho phép đặt lịch", activeHint: "Khách hàng có thể đặt dịch vụ khi đang hoạt động.", options: "Tuỳ chọn", optionsDescription: "Thêm lựa chọn như kiểu dáng, kích thước hoặc màu.", addOptionGroup: "Thêm nhóm tuỳ chọn", remove: "Xoá", cancel: "Huỷ", reset: "Đặt lại", save: "Lưu dịch vụ", saving: "Đang lưu…", create: "Tạo dịch vụ", creating: "Đang tạo…", preview: "Xem trước cho khách", previewDescription: "Đây là cách dịch vụ hiển thị trong luồng đặt lịch.", loadError: "Không thể tải dịch vụ", saveError: "Không thể lưu dịch vụ", categoriesError: "Không thể tải danh mục", retry: "Thử lại", imagePreview: "Xem trước ảnh dịch vụ", option: "Tuỳ chọn dịch vụ", optionPlaceholder: "Ví dụ: Kiểu dáng, kích thước", valuePlaceholder: "Giá trị", pricePlaceholder: "Giá", minutesPlaceholder: "Phút", required: "Bắt buộc", addValue: "Thêm giá trị", previewImage: "Ảnh dịch vụ", previewCategory: "Danh mục", previewFrom: "Từ", previewTotal: "Tổng cộng", previewBook: "Đặt lịch" },
};
export default service;
