import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, ReceiptText, Settings2 } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { useShopMembership } from "@/features/shop/membership/hooks/useShopMembership";
import { adjustPayroll, confirmPayroll, getPayroll, payPayroll } from "../services/payrollService";
import type { CommissionType, PaymentMethod, Payroll, SalaryConfigInput, SalaryPeriod, ServiceCommission } from "../types/payroll";
import { getApiError, payrollStatusClass } from "../utils/payroll";

const money = (value: number, locale: string) => new Intl.NumberFormat(locale, { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(value);
const methods: PaymentMethod[] = ["CASH", "TRANSFER", "CARD", "MOMO", "VNPAY", "ZALO_PAY"];

export default function PayrollDetail() {
  const { t, i18n } = useTranslation(["payroll", "common"]); const locale = i18n.resolvedLanguage?.startsWith("vi") ? "vi-VN" : "en-US";
  const { shopSlug = "", payrollId = "" } = useParams<{ shopSlug: string; payrollId: string }>(); const navigate = useNavigate(); const { membership } = useShopMembership(); const isOwner = membership?.role === "OWNER";
  const [payroll, setPayroll] = useState<Payroll | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const [adjustOpen, setAdjustOpen] = useState(false); const [adjustType, setAdjustType] = useState<"BONUS" | "DEDUCTION">("BONUS"); const [adjustAmount, setAdjustAmount] = useState(""); const [adjustReason, setAdjustReason] = useState("");
  const [adjustError, setAdjustError] = useState("");
  const [confirmOpen, setConfirmOpen] = useState(false); const [payOpen, setPayOpen] = useState(false); const [method, setMethod] = useState<PaymentMethod>("TRANSFER"); const [paymentNote, setPaymentNote] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(null); try { setPayroll(await getPayroll(shopSlug, payrollId)); } catch (e) { setError(getApiError(e)); } finally { setLoading(false); } }, [shopSlug, payrollId]);
  useEffect(() => { void load(); }, [load]);
  const action = async (work: () => Promise<Payroll>, success: string) => { setBusy(true); try { setPayroll(await work()); toast.success(success); return true; } catch (e) { toast.error(t("errors.action"), { description: getApiError(e) }); return false; } finally { setBusy(false); } };
  const submitAdjustment = async () => { const amount = Number(adjustAmount); if (!(amount > 0) || adjustReason.trim().length < 3) { setAdjustError(t("adjust.validation")); return; } setAdjustError(""); if (await action(() => adjustPayroll(shopSlug, payrollId, { type: adjustType, amount, description: adjustReason.trim() }), t("adjust.success"))) { setAdjustOpen(false); setAdjustAmount(""); setAdjustReason(""); } };
  if (loading) return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1400px] space-y-4"><Skeleton className="h-10 w-72" /><Skeleton className="h-36" /><Skeleton className="h-80" /></div></main>;
  if (error || !payroll) return <main className="p-4 sm:p-6 lg:p-8"><Card className="mx-auto max-w-2xl"><CardContent className="flex min-h-64 flex-col items-center justify-center text-center"><p className="font-semibold">{t("loadError")}</p><p role="alert" className="mt-2 text-sm text-muted-foreground">{error}</p><Button variant="outline" className="mt-4" onClick={() => void load()}>{t("common:actions.tryAgain")}</Button></CardContent></Card></main>;
  const stats = [["detail.base", payroll.baseSalary], ["detail.commission", payroll.commissionTotal], ["detail.bonus", payroll.bonusTotal + payroll.otherBonuses], ["detail.overtime", payroll.otAmount], ["detail.penalties", payroll.penaltyTotal], ["detail.otherDeductions", payroll.otherDeductions]] as const;
  return <main className="min-h-full bg-background text-foreground"><div className="mx-auto w-full max-w-[1400px] space-y-5 px-4 py-6 sm:px-6 lg:px-8">
    <header><Button variant="ghost" className="-ml-3" onClick={() => navigate(`/shops/${shopSlug}/admin/payroll`)}><ArrowLeft aria-hidden="true" />{t("detail.back")}</Button><div className="mt-3 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{payroll.user?.name ?? payroll.user?.email ?? t("detail.title")}</h1><Badge className={payrollStatusClass(payroll.status)}>{t(`statuses.${payroll.status.toLowerCase()}`)}</Badge></div><p className="mt-1.5 text-sm tabular-nums text-muted-foreground">{new Date(payroll.periodStart).toLocaleDateString(locale)} – {new Date(payroll.periodEnd).toLocaleDateString(locale)}</p></div><div className="flex flex-wrap gap-2">{payroll.status === "DRAFT" && <Button variant="outline" onClick={() => setAdjustOpen(true)}><Settings2 aria-hidden="true" />{t("adjust.action")}</Button>}{isOwner && payroll.status === "DRAFT" && <Button onClick={() => setConfirmOpen(true)}>{t("confirm.action")}</Button>}{isOwner && payroll.status === "CONFIRMED" && <Button onClick={() => setPayOpen(true)}>{t("pay.action")}</Button>}</div></div></header>
    <section className="grid gap-3 md:grid-cols-3"><Card className="md:col-span-2"><CardHeader><CardTitle>{t("detail.overview")}</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4 sm:grid-cols-4"><div><p className="text-xs text-muted-foreground">{t("detail.gross")}</p><p className="mt-1 text-lg font-bold tabular-nums">{money(payroll.grossAmount, locale)}</p></div><div><p className="text-xs text-muted-foreground">{t("detail.net")}</p><p className="mt-1 text-lg font-bold tabular-nums text-primary">{money(payroll.netAmount, locale)}</p></div><div><p className="text-xs text-muted-foreground">{t("detail.workDays")}</p><p className="mt-1 text-lg font-bold tabular-nums">{payroll.totalWorkDays}</p></div><div><p className="text-xs text-muted-foreground">{t("detail.services")}</p><p className="mt-1 text-lg font-bold tabular-nums">{payroll.totalServices}</p></div></CardContent></Card><Card><CardHeader><CardTitle>{t("detail.activity")}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p className="flex justify-between"><span className="text-muted-foreground">{t("detail.workTime")}</span><span className="font-medium tabular-nums">{Math.floor(payroll.totalWorkMinutes / 60)}h {payroll.totalWorkMinutes % 60}m</span></p><p className="flex justify-between"><span className="text-muted-foreground">{t("detail.revenue")}</span><span className="font-medium tabular-nums">{money(payroll.totalRevenue, locale)}</span></p></CardContent></Card></section>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(320px,.45fr)]"><div className="space-y-5"><Card><CardHeader><CardTitle>{t("detail.breakdown")}</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{stats.map(([label, value]) => <div key={label} className="flex items-center justify-between rounded-lg border p-3"><span className="text-sm text-muted-foreground">{t(label)}</span><span className="font-semibold tabular-nums">{money(value, locale)}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>{t("detail.lineItems")}</CardTitle></CardHeader><CardContent>{payroll.lineItems.length ? <div className="divide-y">{payroll.lineItems.map((item, index) => <div key={`${item.referenceId ?? item.type}-${index}`} className="flex items-start justify-between gap-4 py-3"><div className="min-w-0"><p className="text-sm font-medium">{item.description}</p><p className="mt-1 text-xs text-muted-foreground">{item.type}{item.date ? ` · ${new Date(item.date).toLocaleDateString(locale)}` : ""}</p></div><span className="shrink-0 font-mono text-sm tabular-nums">{money(item.amount, locale)}</span></div>)}</div> : <div className="flex min-h-32 flex-col items-center justify-center text-center text-sm text-muted-foreground"><ReceiptText className="mb-3 size-8" aria-hidden="true" />{t("detail.noItems")}</div>}</CardContent></Card></div>
      <div className="space-y-5"><Card><CardHeader><CardTitle>{t("detail.title")}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{payroll.approvedAt && <p className="flex justify-between gap-3"><span className="text-muted-foreground">{t("detail.approvedAt")}</span><span className="text-right tabular-nums">{new Date(payroll.approvedAt).toLocaleString(locale)}</span></p>}{payroll.paidAt && <p className="flex justify-between gap-3"><span className="text-muted-foreground">{t("detail.paidAt")}</span><span className="text-right tabular-nums">{new Date(payroll.paidAt).toLocaleString(locale)}</span></p>}{payroll.paymentMethod && <p className="flex justify-between"><span className="text-muted-foreground">{t("detail.paymentMethod")}</span><span>{payroll.paymentMethod}</span></p>}{payroll.paymentNote && <p className="rounded-lg bg-muted/35 p-3 text-muted-foreground">{payroll.paymentNote}</p>}</CardContent></Card></div></section>
  </div>
  <Sheet open={adjustOpen} onOpenChange={setAdjustOpen}><SheetContent className="w-full sm:max-w-md"><SheetHeader><SheetTitle>{t("adjust.title")}</SheetTitle><SheetDescription>{t("adjust.description")}</SheetDescription></SheetHeader><div className="space-y-4 px-4"><div className="space-y-1.5"><Label>{t("adjust.type")}</Label><Select value={adjustType} onValueChange={(v) => setAdjustType(v as typeof adjustType)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="BONUS">{t("adjust.bonus")}</SelectItem><SelectItem value="DEDUCTION">{t("adjust.deduction")}</SelectItem></SelectContent></Select></div><div className="space-y-1.5"><Label htmlFor="adjust-amount">{t("adjust.amount")}</Label><Input id="adjust-amount" type="number" min="1" inputMode="numeric" value={adjustAmount} aria-describedby={adjustError ? "adjust-error" : undefined} onChange={(e) => { setAdjustAmount(e.target.value); setAdjustError(""); }} /></div><div className="space-y-1.5"><Label htmlFor="adjust-reason">{t("adjust.reason")}</Label><Textarea id="adjust-reason" value={adjustReason} aria-describedby={adjustError ? "adjust-error" : undefined} onChange={(e) => { setAdjustReason(e.target.value); setAdjustError(""); }} placeholder={t("adjust.reasonPlaceholder")} /></div>{adjustError && <p id="adjust-error" role="alert" className="text-sm text-destructive">{adjustError}</p>}</div><SheetFooter><Button variant="outline" onClick={() => setAdjustOpen(false)}>{t("common:actions.cancel")}</Button><Button disabled={busy} onClick={() => void submitAdjustment()}>{busy ? t("adjust.saving") : t("adjust.action")}</Button></SheetFooter></SheetContent></Sheet>
  <AlertDialog open={confirmOpen} onOpenChange={setConfirmOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t("confirm.title")}</AlertDialogTitle><AlertDialogDescription>{t("confirm.description")}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{t("common:actions.cancel")}</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async (e) => { e.preventDefault(); if (await action(() => confirmPayroll(shopSlug, payrollId), t("confirm.success"))) setConfirmOpen(false); }}>{busy ? t("confirm.working") : t("confirm.action")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <AlertDialog open={payOpen} onOpenChange={setPayOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t("pay.title")}</AlertDialogTitle><AlertDialogDescription>{t("pay.description")}</AlertDialogDescription></AlertDialogHeader><div className="space-y-4"><div className="space-y-1.5"><Label>{t("pay.method")}</Label><Select value={method} onValueChange={(v) => setMethod(v as PaymentMethod)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{methods.map((v) => <SelectItem key={v} value={v}>{v.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label htmlFor="payment-note">{t("pay.note")}</Label><Textarea id="payment-note" value={paymentNote} onChange={(e) => setPaymentNote(e.target.value)} placeholder={t("pay.notePlaceholder")} /></div></div><AlertDialogFooter><AlertDialogCancel>{t("common:actions.cancel")}</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async (e) => { e.preventDefault(); if (await action(() => payPayroll(shopSlug, payrollId, { paymentMethod: method, paymentNote: paymentNote || undefined }), t("pay.success"))) setPayOpen(false); }}>{busy ? t("pay.working") : t("pay.action")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}

export function SalarySettings({ config, commissions, loading, busy, locale, onConfig, onNumber, onSaveConfig, onCommission, onSaveCommission }: { config: SalaryConfigInput; commissions: ServiceCommission[]; loading: boolean; busy: boolean; locale: string; onConfig: React.Dispatch<React.SetStateAction<SalaryConfigInput>>; onNumber: (key: keyof SalaryConfigInput, value: string) => void; onSaveConfig: () => Promise<void>; onCommission: React.Dispatch<React.SetStateAction<ServiceCommission[]>>; onSaveCommission: (item: ServiceCommission) => Promise<void> }) {
  const { t } = useTranslation("payroll"); if (loading) return <Skeleton className="h-80" />;
  const numeric: [keyof SalaryConfigInput, string][] = [["baseSalary","baseSalary"],["defaultCommissionPercent","defaultPercent"],["defaultFixedPerService","defaultFixed"],["bonusPerPositiveReview","reviewBonus"],["penaltyPerNoShow","noShowPenalty"],["penaltyPerLateMinute","latePenalty"],["otMultiplier","otMultiplier"]];
  return <section className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>{t("config.title")}</CardTitle><p className="text-sm text-muted-foreground">{t("config.description")}</p></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>{t("config.commissionType")}</Label><Select value={String(config.commissionType ?? "PERCENT")} onValueChange={(v) => onConfig((x) => ({ ...x, commissionType: v as CommissionType }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{(["PERCENT","FIXED_PER_SERVICE","FIXED_PER_DAY","SALARY"] as CommissionType[]).map((v) => <SelectItem key={v} value={v}>{v.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>{t("config.salaryPeriod")}</Label><Select value={String(config.salaryPeriod ?? "MONTHLY")} onValueChange={(v) => onConfig((x) => ({ ...x, salaryPeriod: v as SalaryPeriod }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{(["WEEKLY","BIWEEKLY","MONTHLY"] as SalaryPeriod[]).map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>{numeric.map(([key, label]) => <div key={key} className="space-y-1.5"><Label htmlFor={`config-${key}`}>{t(`config.${label}`)}</Label><Input id={`config-${key}`} type="number" min="0" step={key === "otMultiplier" ? ".1" : "1"} value={Number(config[key] ?? 0)} onChange={(e) => onNumber(key, e.target.value)} /></div>)}<div className="space-y-1.5"><Label htmlFor="effective-from">{t("config.effectiveFrom")}</Label><Input id="effective-from" type="date" value={String(config.effectiveFrom ?? "")} onChange={(e) => onConfig((x) => ({ ...x, effectiveFrom: e.target.value }))} /></div><div className="space-y-1.5 sm:col-span-2"><Label htmlFor="config-note">{t("config.note")}</Label><Textarea id="config-note" value={String(config.note ?? "")} onChange={(e) => onConfig((x) => ({ ...x, note: e.target.value }))} /></div><Button className="sm:col-span-2" disabled={busy} onClick={() => void onSaveConfig()}>{busy ? t("config.saving") : t("config.save")}</Button></CardContent></Card>
    <Card><CardHeader><CardTitle>{t("commissions.title")}</CardTitle><p className="text-sm text-muted-foreground">{t("commissions.description")}</p></CardHeader><CardContent>{commissions.length === 0 ? <p className="py-12 text-center text-sm text-muted-foreground">{t("commissions.empty")}</p> : <div className="divide-y">{commissions.map((item) => <div key={item.serviceId} className="space-y-3 py-4"><p className="font-medium">{item.service.name}</p><div className="grid grid-cols-[1fr_1fr_auto] items-end gap-2"><div className="space-y-1.5"><Label>{t("commissions.type")}</Label><Select value={item.commissionType} onValueChange={(v) => onCommission((list) => list.map((x) => x.serviceId === item.serviceId ? { ...x, commissionType: v as ServiceCommission["commissionType"] } : x))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="PERCENT">%</SelectItem><SelectItem value="FIXED_PER_SERVICE">{new Intl.NumberFormat(locale).format(0)} VND</SelectItem></SelectContent></Select></div><div className="space-y-1.5"><Label htmlFor={`commission-${item.serviceId}`}>{t("commissions.value")}</Label><Input id={`commission-${item.serviceId}`} type="number" min="0" value={item.value} onChange={(e) => onCommission((list) => list.map((x) => x.serviceId === item.serviceId ? { ...x, value: Number(e.target.value) } : x))} /></div><Button variant="outline" onClick={() => void onSaveCommission(item)}>{t("commissions.save")}</Button></div></div>)}</div>}</CardContent></Card></section>;
}
