import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import dayjs from "@/lib/dayjs";
import { getApiErrorMessage } from "@/lib/getApiErrorMessage";
import { getStaffAttendance, getStaffDetail, getStaffSchedule, getStaffTimeOff, updateStaffSchedule } from "../services/staffService";
import { reviewTimeOffRequest } from "../../workforce/services/workforceService";
import type { Staff, StaffScheduleDay, StaffScheduleOffDay } from "../types/staff";
import type { StaffAttendance } from "../types/staffOperations";
import type { AdminTimeOffRequest } from "../../workforce/types/workforce";
import { buildAttendanceDisplayRecords } from "../utils/staffOperations";

export type AttendanceRangePreset = "WEEK" | "MONTH" | "PREVIOUS_MONTH" | "CUSTOM";
export function useStaffOperations() {
  const { shopSlug = "", staffId = "" } = useParams<{ shopSlug: string; staffId: string }>();
  const [staff, setStaff] = useState<Staff | null>(null); const [schedule, setSchedule] = useState<StaffScheduleDay[]>([]); const [scheduleOffDays, setScheduleOffDays] = useState<StaffScheduleOffDay[]>([]);
  const [attendance, setAttendance] = useState<StaffAttendance[]>([]); const [overviewAttendance, setOverviewAttendance] = useState<StaffAttendance[]>([]); const [timeOff, setTimeOff] = useState<AdminTimeOffRequest[]>([]);
  const [preset, setPreset] = useState<AttendanceRangePreset>("MONTH"); const [customFrom, setCustomFrom] = useState(dayjs().startOf("month").format("YYYY-MM-DD")); const [customTo, setCustomTo] = useState(dayjs().format("YYYY-MM-DD"));
  const [timeOffPage, setTimeOffPage] = useState(1); const [timeOffStatus, setTimeOffStatus] = useState<"ALL" | "PENDING" | "APPROVED" | "REJECTED">("ALL"); const [timeOffMeta, setTimeOffMeta] = useState({ total: 0, page: 1, limit: 10, totalPages: 1, statusCounts: { PENDING: 0, APPROVED: 0, REJECTED: 0 } });
  const [loading, setLoading] = useState(true); const [attendanceLoading, setAttendanceLoading] = useState(false); const [timeOffLoading, setTimeOffLoading] = useState(false); const [savingSchedule, setSavingSchedule] = useState(false); const [reviewingId, setReviewingId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const range = useMemo(() => { const now = dayjs(); if (preset === "WEEK") return { from: now.startOf("week").format("YYYY-MM-DD"), to: now.endOf("week").format("YYYY-MM-DD") }; if (preset === "PREVIOUS_MONTH") { const previous = now.subtract(1, "month"); return { from: previous.startOf("month").format("YYYY-MM-DD"), to: previous.endOf("month").format("YYYY-MM-DD") }; } if (preset === "CUSTOM") return { from: customFrom, to: customTo }; return { from: now.startOf("month").format("YYYY-MM-DD"), to: now.endOf("month").format("YYYY-MM-DD") }; }, [customFrom, customTo, preset]);

  const loadBase = useCallback(async () => { if (!shopSlug || !staffId) return; setLoading(true); setError(null); try { const [profile, workSchedule] = await Promise.all([getStaffDetail(shopSlug, staffId), getStaffSchedule(shopSlug, staffId)]); setStaff(profile); setSchedule(workSchedule.schedule); setScheduleOffDays(workSchedule.offDays); } catch (requestError) { setError(getApiErrorMessage(requestError, "Unable to load staff details")); } finally { setLoading(false); } }, [shopSlug, staffId]);
  const loadAttendance = useCallback(async () => { if (!shopSlug || !staffId || !range.from || !range.to || range.from > range.to) return; setAttendanceLoading(true); try { setAttendance(await getStaffAttendance(shopSlug, staffId, range.from, range.to)); } catch (requestError) { setError(getApiErrorMessage(requestError, "Unable to load attendance")); } finally { setAttendanceLoading(false); } }, [range.from, range.to, shopSlug, staffId]);
  const loadOverviewAttendance = useCallback(async () => { if (!shopSlug || !staffId) return; const now = dayjs(); try { setOverviewAttendance(await getStaffAttendance(shopSlug, staffId, now.startOf("week").format("YYYY-MM-DD"), now.endOf("week").format("YYYY-MM-DD"))); } catch (requestError) { setError(getApiErrorMessage(requestError, "Unable to load this week's attendance")); } }, [shopSlug, staffId]);
  const loadTimeOff = useCallback(async () => { if (!shopSlug || !staffId) return; setTimeOffLoading(true); try { const result = await getStaffTimeOff(shopSlug, staffId, timeOffPage, timeOffStatus === "ALL" ? undefined : timeOffStatus); setTimeOff(result.data); setTimeOffMeta(result.meta); } catch (requestError) { setError(getApiErrorMessage(requestError, "Unable to load time off")); } finally { setTimeOffLoading(false); } }, [shopSlug, staffId, timeOffPage, timeOffStatus]);
  useEffect(() => { void loadBase(); }, [loadBase]); useEffect(() => { void loadAttendance(); }, [loadAttendance]); useEffect(() => { void loadOverviewAttendance(); }, [loadOverviewAttendance]); useEffect(() => { void loadTimeOff(); }, [loadTimeOff]);
  const records = useMemo(() => buildAttendanceDisplayRecords(range.from, range.to, schedule, attendance, scheduleOffDays), [attendance, range.from, range.to, schedule, scheduleOffDays]);
  const overviewRecords = useMemo(() => { const now = dayjs(); return buildAttendanceDisplayRecords(now.startOf("week").format("YYYY-MM-DD"), now.endOf("week").format("YYYY-MM-DD"), schedule, overviewAttendance, scheduleOffDays); }, [overviewAttendance, schedule, scheduleOffDays]);
  const saveSchedule = useCallback(async (_staffId: string, days: StaffScheduleDay[]) => { setSavingSchedule(true); try { const saved = await updateStaffSchedule(shopSlug, staffId, days); setSchedule(saved); return true; } catch (requestError) { setError(getApiErrorMessage(requestError, "Unable to update schedule")); return false; } finally { setSavingSchedule(false); } }, [shopSlug, staffId]);
  const reviewTimeOff = useCallback(async (requestId: string, input: { status: "APPROVED" | "REJECTED"; rejectReason?: string }) => { setReviewingId(requestId); try { await reviewTimeOffRequest(shopSlug, requestId, input); await Promise.all([loadTimeOff(), loadBase(), loadAttendance(), loadOverviewAttendance()]); return true; } catch (requestError) { setError(getApiErrorMessage(requestError, "Unable to review time off")); return false; } finally { setReviewingId(null); } }, [loadAttendance, loadBase, loadOverviewAttendance, loadTimeOff, shopSlug]);
  return { shopSlug, staffId, staff, schedule, scheduleOffDays, records, overviewRecords, range, preset, setPreset, customFrom, setCustomFrom, customTo, setCustomTo, timeOff, timeOffMeta, timeOffPage, setTimeOffPage, timeOffStatus, setTimeOffStatus, loading, attendanceLoading, timeOffLoading, savingSchedule, reviewingId, error, reload: () => Promise.all([loadBase(), loadAttendance(), loadOverviewAttendance(), loadTimeOff()]), saveSchedule, reviewTimeOff };
}
